apiVersion: v1
kind: Service
metadata:
  name: blockscout
  namespace: l2launcher
spec:
  selector:
    name: blockscout
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
