apiVersion: v1
kind: Service
metadata:
  name: blockscout-postgres
  namespace: l2launcher
spec:
  selector:
    name: blockscout-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
