apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
  namespace: l2launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: blockscout
  template:
    metadata:
      labels:
        name: blockscout
    spec:
      containers:
        - args:
            - sh
            - -c
            - bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start
          env:
            - name: ACCOUNT_ENABLED
              value: "false"
            - name: API_V1_READ_METHODS_DISABLED
              value: "false"
            - name: API_V1_WRITE_METHODS_DISABLED
              value: "false"
            - name: API_V2_ENABLED
              value: "true"
            - name: APPS_MENU
              value: "false"
            - name: BLOCK_TRANSFORMER
              value: base
            - name: CHAIN_ID
            - name: CHAIN_SPEC_PATH
              value: /genesis.json
            - name: CHECKSUM_ADDRESS_HASHES
              value: "true"
            - name: CHECKSUM_FUNCTION
              value: eth
            - name: DATABASE_URL
              value: postgresql://postgres:@blockscout-postgres:5432/blockscout?ssl=false
            - name: DECODE_NOT_A_CONTRACT_CALLS
              value: "true"
            - name: DISABLE_EXCHANGE_RATES
              value: "true"
            - name: DISABLE_INDEXER
              value: "false"
            - name: DISABLE_REALTIME_INDEXER
              value: "false"
            - name: DISABLE_WEBAPP
              value: "false"
            - name: DISPLAY_TOKEN_ICONS
              value: "false"
            - name: ECTO_USE_SSL
              value: "false"
            - name: EIP_1559_ELASTICITY_MULTIPLIER
              value: "2"
            - name: EMISSION_FORMAT
              value: DEFAULT
            - name: ETHEREUM_JSONRPC_HTTP_URL
              value: http://op-geth:8545/
            - name: ETHEREUM_JSONRPC_TRACE_URL
              value: http://op-geth:8545/
            - name: ETHEREUM_JSONRPC_VARIANT
              value: geth
            - name: EXTERNAL_APPS
              value: '[]'
            - name: FETCH_REWARDS_WAY
              value: trace_block
            - name: FOOTER_LINK_TO_OTHER_EXPLORERS
              value: "false"
            - name: FOOTER_OTHER_EXPLORERS
              value: '{}'
            - name: HIDE_BLOCK_MINER
              value: "false"
            - name: INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER
              value: "false"
            - name: INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER
              value: "false"
            - name: INDEXER_DISABLE_TOKEN_INSTANCE_LEGACY_SANITIZE_FETCHER
              value: "false"
            - name: INDEXER_DISABLE_TOKEN_INSTANCE_REALTIME_FETCHER
              value: "false"
            - name: INDEXER_DISABLE_TOKEN_INSTANCE_RETRY_FETCHER
              value: "false"
            - name: INDEXER_DISABLE_TOKEN_INSTANCE_SANITIZE_FETCHER
              value: "false"
            - name: MICROSERVICE_SC_VERIFIER_ENABLED
              value: "true"
            - name: MICROSERVICE_SC_VERIFIER_TYPE
              value: sc_verifier
            - name: MICROSERVICE_SC_VERIFIER_URL
              value: http://blockscout-smart-contract-verifier:8050/
            - name: MICROSERVICE_SIG_PROVIDER_ENABLED
              value: "true"
            - name: MICROSERVICE_SIG_PROVIDER_URL
              value: http://blockscout-sig-provider:8050/
            - name: MICROSERVICE_VISUALIZE_SOL2UML_ENABLED
              value: "true"
            - name: MICROSERVICE_VISUALIZE_SOL2UML_URL
              value: http://blockscout-visualizer:8050/
            - name: NETWORK_PATH
              value: /
            - name: POOL_SIZE
              value: "80"
            - name: POOL_SIZE_API
              value: "10"
            - name: PORT
              value: "4000"
            - name: RE_CAPTCHA_DISABLED
              value: "false"
            - name: SECRET_KEY_BASE
              value: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN
            - name: SHOW_ADDRESS_MARKETCAP_PERCENTAGE
              value: "true"
            - name: SHOW_MAINTENANCE_ALERT
              value: "false"
            - name: SHOW_PRICE_CHART
              value: "false"
            - name: SHOW_PRICE_CHART_LEGEND
              value: "false"
            - name: SHOW_TENDERLY_LINK
              value: "false"
            - name: SHOW_TXS_CHART
              value: "true"
            - name: SUBNETWORK
              value: 'L2 CHAIN '
            - name: SUPPORTED_CHAINS
              value: '{}'
            - name: TXS_STATS_ENABLED
              value: "true"
          image: blockscout/blockscout
          name: blockscout
          ports:
            - containerPort: 4000
              protocol: TCP
          volumeMounts:
            - mountPath: /genesis.json
              name: genesis-pvc
              readOnly: true
      volumes:
        - name: genesis-pvc
          persistentVolumeClaim:
            claimName: genesis-pvc
            readOnly: true
