apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout-postgres
  namespace: l2launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: blockscout-postgres
  template:
    metadata:
      labels:
        name: blockscout-postgres
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=200
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: postgres
          image: postgres:14
          name: blockscout-postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: blockscout-postgres-pvc
      volumes:
        - name: blockscout-postgres-pvc
          persistentVolumeClaim:
            claimName: blockscout-postgres-pvc
