apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-geth
  namespace: l2launcher
spec:
  selector:
    matchLabels:
      name: op-geth
  replicas: 1
  template:
    metadata:
      labels:
        name: op-geth
    spec:
      initContainers:
        - image: ghcr.io/planetarium/mothership-l2launcher-genesis-deployer:latest
          name: genesis-deployer
          volumeMounts:
            - mountPath: /data
              name: genesis-pvc
          env:
            - name: L1_RPC
              valueFrom:
                configMapKeyRef:
                  name: env-cm
                  key: L1_RPC
            - name: L2_CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: env-cm
                  key: L2_CHAIN_ID
            - name: ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: ADMIN_KEY
            - name: BATCHER_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: BATCHER_KEY
            - name: PROPOSER_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: PROPOSER_KEY
            - name: SEQUENCER_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: SEQUENCER_KEY
        - image: ghcr.io/planetarium/mothership-l2launcher-genesis-init-predeploy:latest
          name: genesis-init-predeploy
          volumeMounts:
            - mountPath: /data
              name: op-geth-pvc
            - mountPath: /genesis
              name: genesis-pvc
            - mountPath: /genesis/predeploy.json
              name: predeploy-json-cm
              subPath: predeploy.json
              readOnly: true
      containers:
        - args:
            - --datadir=/data
            - --http
            - --http.corsdomain=*
            - --http.vhosts=*
            - --http.addr=0.0.0.0
            - --http.api=web3,debug,eth,txpool,net,engine
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port=8546
            - --ws.origins=*
            - --ws.api=debug,eth,txpool,net,engine
            - --syncmode=full
            - --gcmode=archive
            - --nodiscover
            - --maxpeers=0
            - --authrpc.vhosts=*
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/genesis/jwt.txt
            - --rollup.disabletxpoolgossip=true
          image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101305.0
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "8545"
            periodSeconds: 5
          name: op-geth
          ports:
            - containerPort: 8545
              protocol: TCP
            - containerPort: 8546
              protocol: TCP
            - containerPort: 8551
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: op-geth-pvc
            - mountPath: /genesis
              name: genesis-pvc
              readOnly: true
      volumes:
        - name: genesis-pvc
          persistentVolumeClaim:
            claimName: genesis-pvc
        - name: op-geth-pvc
          persistentVolumeClaim:
            claimName: op-geth-pvc
        - name: predeploy-json-cm
          configMap:
            name: predeploy-json-cm
