apiVersion: v1
kind: Service
metadata:
  name: op-geth
  namespace: l2launcher
spec:
  selector:
    name: op-geth
  ports:
    - protocol: TCP
      name: rpc
      port: 8545
      targetPort: 8545
    - protocol: TCP
      name: wsrpc
      port: 8546
      targetPort: 8546
    - protocol: TCP
      name: authrpc
      port: 8551
      targetPort: 8551
