apiVersion: v1
kind: Service
metadata:
  name: op-node
  namespace: l2launcher
spec:
  selector:
    name: op-node
  ports:
    - protocol: TCP
      name: rpc
      port: 8547
      targetPort: 8547
    - protocol: TCP
      name: p2p
      port: 9003
