apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: op-node
  namespace: l2launcher
spec:
  selector:
    matchLabels:
      name: op-node
  serviceName: op-node
  replicas: 3
  template:
    metadata:
      labels:
        name: op-node
    spec:
      initContainers:
        - name: genesis-deployer
          image: ghcr.io/planetarium/mothership-l2launcher-genesis-deployer:latest
          env:
            - name: L1_RPC
              valueFrom:
                configMapKeyRef:
                  name: env-cm
                  key: L1_RPC
            - name: L2_CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: env-cm
                  key: L2_CHAIN_ID
            - name: ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: ADMIN_KEY
            - name: BATCHER_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: BATCHER_KEY
            - name: PROPOSER_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: PROPOSER_KEY
            - name: SEQUENCER_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: SEQUENCER_KEY
          volumeMounts:
            - mountPath: /data
              name: genesis-pvc
        - name: genesis-init-predeploy
          image: ghcr.io/planetarium/mothership-l2launcher-genesis-init-predeploy:latest
          volumeMounts:
            - mountPath: /data
              name: op-geth-volume
            - mountPath: /genesis
              name: genesis-pvc
            - mountPath: /genesis/predeploy.json
              name: predeploy-json-cm
              subPath: predeploy.json
              readOnly: true
      containers:
        - name: op-geth
          image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101305.0
          args:
            - --datadir=/data
            - --http
            - --http.corsdomain=*
            - --http.vhosts=*
            - --http.addr=0.0.0.0
            - --http.api=web3,debug,eth,txpool,net,engine
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port=8546
            - --ws.origins=*
            - --ws.api=debug,eth,txpool,net,engine
            - --syncmode=full
            - --gcmode=archive
            - --nodiscover
            - --maxpeers=0
            - --authrpc.vhosts=*
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/genesis/jwt.txt
            - --rollup.disabletxpoolgossip=true
          ports:
            - containerPort: 8545
              protocol: TCP
            - containerPort: 8546
              protocol: TCP
            - containerPort: 8551
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: op-geth-volume
            - mountPath: /genesis
              name: genesis-pvc
              readOnly: true
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "8545"
            periodSeconds: 5
        - name: op-node
          image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.4.2
          command:
            - sh
            - -c
          args:
            - |
              op-node \
                --l1=$(L1_RPC) \
                --l1.rpckind=any \
                --l2=http://localhost:8551 \
                --l2.jwt-secret=/genesis/jwt.txt \
                --rollup.config=/genesis/rollup.json \
                --rpc.addr=0.0.0.0 \
                --rpc.port=8547 \
                --rpc.enable-admin \
                --p2p.listen.ip=0.0.0.0 \
                --p2p.listen.tcp=9003 \
                --p2p.sequencer.key=$${SEQUENCER_KEY#0x} \
                --sequencer.enabled=$$([[ $K8S_NODE_NAME = "op-node-0" ]] && echo "true" || echo "false")
                --sequencer.l1-confs=3 \
                --verifier.l1-confs=3 \
                --log.level=debug
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: L1_RPC
              valueFrom:
                configMapKeyRef:
                  name: env-cm
                  key: L1_RPC
            - name: SEQUENCER_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: SEQUENCER_KEY
          ports:
            - containerPort: 8547
              protocol: TCP
            - containerPort: 9003
              protocol: TCP
            - containerPort: 9003
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: op-node-volume
            - mountPath: /genesis
              name: genesis-pvc
              readOnly: true
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "8547"
            periodSeconds: 5
      volumes:
        - name: genesis-pvc
          persistentVolumeClaim:
            claimName: genesis-pvc
        - name: predeploy-json-cm
          configMap:
            name: predeploy-json-cm
  volumeClaimTemplates:
  - metadata:
      name: op-geth-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: op-node-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
