version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ../data/blockscout/postgres:/var/lib/postgresql/data/
