apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genesis-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.genesis.volume.storage }}
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{ end }}
  volumeMode: Filesystem
