apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genesis-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
