externalSecret:
  enabled: false

genesis:
  volume: &genesis-volume
    storage: 100Mi
  genesisDeployer:
    image: &genesis-deployer-image ghcr.io/planetarium/mothership-l2launcher-genesis-deployer:latest
  genesisInitPredeploy:
    image: &genesis-init-predeploy-image ghcr.io/planetarium/mothership-l2launcher-genesis-init-predeploy:latest

node:
  replicas: 1
  loadBalancerExternal: false
  opGeth:
    image: &op-geth-image us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101308.0
    port: &op-geth-port
      rpc: 8545
      wsrpc: 8546
      authrpc: 8551
    volume: &op-geth-volume
      storage: 100Gi
  opNode:
    image: &op-node-image us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.5.1
    port: &op-node-port
      rpc: 8547
      p2p: 9222
    volume: &op-node-volume
      storage: 100Mi

sequencer:
  replicas: 0
  opGeth:
    image: *op-geth-image
    port:
      <<: *op-geth-port
    volume:
      <<: *op-geth-volume
  opNode:
    image: *op-node-image
    port:
      <<: *op-node-port
    volume:
      <<: *op-node-volume

opBatcher:
  replicas: 0
  image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.5.1
  port:
    rpc: 8548

opProposer:
  replicas: 0
  image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:v1.5.1
  port:
    rpc: 8560

blockscout:
  port: 5000
  loadBalancerExternal: false
  db:
    storage: 10Gi
