nodes:
  replicas: 1
  opGeth:
    image: &op-geth-image us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101305.0
    port: &op-geth-port
      rpc: 8545
      wsrpc: 8546
      authrpc: 8551
  opNode:
    image: &op-node-image us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.4.2
    port: &op-node-port
      rpc: 8547
      p2p: 9222
  genesisDeployer:
    image: &genesis-deployer-image ghcr.io/planetarium/mothership-l2launcher-genesis-deployer:latest
  genesisInitPredeploy:
    image: &genesis-init-predeploy-image ghcr.io/planetarium/mothership-l2launcher-genesis-init-predeploy:latest

sequencer:
  opGeth:
    image: *op-geth-image
    port:
      <<: *op-geth-port
  opNode:
    image: *op-node-image
    port:
      <<: *op-node-port
  genesisDeployer:
    image: *genesis-deployer-image
  genesisInitPredeploy:
    image: *genesis-init-predeploy-image

opBatcher:
  image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.4.2
  port:
    rpc: 8548

opProposer:
  image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:v1.4.2
  port:
    rpc: 8560

blockscout:
  port: 5000
